# See https://github.com/londonmedicallaboratory/view-bundle for latest version

framework:
    cache:
        pools:
            view_cache_pool:    # default pool name; use redis if possible
                tags: true      # adapter must allow tagging items

lml_view:
    cache_pool: view_cache_pool # this is the name of your pool
